apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-application
  labels:
    app: trading-application

spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-application

  template:
    metadata:
      labels:
        app: trading-application
    spec:
      containers:
        - name: trading-application
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1