apiVersion: v1
kind: Service
metadata:
  name: trading-application
  labels:
    app: trading-application
spec:
  selector:
    app: trading-application

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer