FROM openjdk:17
ADD /home/runner/work/trading-application/trading-application/target/trading-aplication-2.5.2.jar trading-application.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","trading-application.jar"]
