name: Dependabot

on:
  push:
    - "*"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run Dependabot
        run: npx dependabot --allow-dirty
      - name: Commit changes
        run: |
          git config --global user.name 'Dependabot'
          git config --global user.email 'dependabot@users.noreply.github.com'
          git add .
          git commit -m "chore(deps): Update dependencies"
          git push
