name: "GitFlow Hotfix Finish"

on:
  push:

env:
  AWS_REGION: "us-east-1"
  TILLSTER_SHARED_ACCESS_KEY: ${{ secrets.TILLSTER_SHARED_ACCESS_KEY }}
  TILLSTER_SHARED_SECRET_KEY: ${{ secrets.TILLSTER_SHARED_SECRET_KEY }}

jobs:
  vault:
    uses: tillster/devops-automation/.github/workflows/workflow_vault.yaml@aggr-tweaks
    with:
      github_runner: "tce-self-hosted"
      vault_path: |
        kv-v2/defaults/security/docker/tce-docker
        kv-v2/serverless-apps/pact-broker
        kv-v2/defaults/infrastructure/cicd/codebuild/tce
    secrets:
      GIT_TOKEN_PAT: ${{ secrets.GH_PAT }}
      TCE_VAULT_TOKEN: ${{ secrets.TCE_VAULT_TOKEN }}
      TILLSTER_VAULT_TOKEN: ${{ secrets.TILLSTER_VAULT_TOKEN }}

  build_java_artifact:
    needs: vault
    name: run_gitflow_hotfix_finish
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ "tce-self-hosted" ]
        region: [ "us-east-1" ]
        environment: [ "dev" ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: "Setup"
        uses: tillster/spi-cicd-actions/gitflow-common@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: "Run Hotfix-Finish"
        shell: bash
        run: |
            BRANCHES=$(git branch -r --format='%(refname:lstrip=-1)' | grep hotfix)
            if [[ $(echo ${BRANCHES} | wc -l) != 1 ]]; then
              echo THERE IS MORE THAN ONE HOTFIX BRANCH, THIS ONLY WORKS WITH ONE
              exit 1;
            fi
            git fetch origin ${BRANCHES}:${BRANCHES}
            ./mvnw -B gitflow:hotfix-finish -D hotfixBranch=${BRANCHES} -s ./tillster-maven/settings.xml -DargLine='-s ./tillster-maven/settings.xml'
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
